version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: movies
    ports:
      - "3306:3306"
    
  mongodb:
    image: percona/percona-server-mongodb:6.0.6
    container_name: mongodb
    ports:
      - "27017:27017"

  spark-master:
    image: bitnami/spark:3.2.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./jars:/jars
  spark-worker:
    image: bitnami/spark:3.2.3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
      - ./jars:/jars