apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
  labels:
    volume: airflow-dags
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/airflow/dags # minikube's shared directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard